FROM python:3.8-slim-buster

RUN apt-get update && apt-get install -y \
  git \
  python3 \
  python3-pip

RUN pip3 install -q \
    fastapi==0.78.0 \
    uvicorn[standard] \
    python-multipart==0.0.5 \
    tritonclient[grpc]==2.23.0 \
    Pillow~=9.2.0 \
    scipy~=1.8.1

WORKDIR /workspace
