FROM nvcr.io/nvidia/pytorch:22.05-py3

RUN pip3 install transformers onnxruntime onnx soundfile

RUN pip3 install torchaudio==0.12.0+cu116 -f https://download.pytorch.org/whl/cu116/torch_stable.html

WORKDIR /workspace

ADD extract_onnx_models.py